name:                BlockChat
version:             0.1.0.0
github:              "steve-anunknown/BlockChat"
license:             BSD-3-Clause
author:              "Stefanos Anagnostou"
maintainer:          "stefanos.anagnostou@outlook.com"
copyright:           "2024 Stefanos Anagnostou"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/steve-anunknown/BlockChat#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- bytestring
- unix-time
- random
- RSA
- crypto-api
- network-simple
- binary
- cryptonite
- memory
- mtl

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  BlockChat-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - BlockChat

tests:
  BlockChat-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - BlockChat
